### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/feeder/feed
Content-Type: application/json

{
  "commands": [
    {
      "type": "Setup",
      "source": "test1",
      "commandName": "setup-iris",
      "maybeObsId": "test-obsId1",
      "paramSet": [
        {
          "keyName": "myStruct",
          "keyType": "StructKey",
          "values": [
            {
              "paramSet": [
                {
                  "keyName": "ra",
                  "keyType": "StringKey",
                  "values": [
                    "12:13:14.1"
                  ],
                  "units": "NoUnits"
                }
              ]
            }
          ],
          "units": "NoUnits"
        }
      ],
      "runId": "196e0354-ea0f-4547-a3df-e04633b704f8"
    },
    {
      "type": "Setup",
      "source": "test1",
      "commandName": "setup-iris",
      "maybeObsId": "test-obsId1",
      "paramSet": [
        {
          "keyName": "myStruct",
          "keyType": "StructKey",
          "values": [
            {
              "paramSet": [
                {
                  "keyName": "ra",
                  "keyType": "StringKey",
                  "values": [
                    "12:13:14.1"
                  ],
                  "units": "NoUnits"
                },
                {
                  "keyName": "dec",
                  "keyType": "StringKey",
                  "values": [
                    "32:33:34.4"
                  ],
                  "units": "NoUnits"
                },
                {
                  "keyName": "epoch",
                  "keyType": "DoubleKey",
                  "values": [
                    1950.0
                  ],
                  "units": "NoUnits"
                }
              ]
            }
          ],
          "units": "NoUnits"
        }
      ],
      "runId": "196e0354-ea0f-4547-a3df-e04633b704f9"
    },
    {
      "type": "Setup",
      "source": "test1",
      "commandName": "setup-iris",
      "maybeObsId": "test-obsId1",
      "paramSet": [
        {
          "keyName": "myStruct",
          "keyType": "StructKey",
          "values": [
            {
              "paramSet": [
                {
                  "keyName": "ra",
                  "keyType": "StringKey",
                  "values": [
                    "12:13:14.1"
                  ],
                  "units": "NoUnits"
                },
                {
                  "keyName": "dec",
                  "keyType": "StringKey",
                  "values": [
                    "32:33:34.4"
                  ],
                  "units": "NoUnits"
                },
                {
                  "keyName": "epoch",
                  "keyType": "DoubleKey",
                  "values": [
                    1950.0
                  ],
                  "units": "NoUnits"
                }
              ]
            }
          ],
          "units": "NoUnits"
        }
      ],
      "runId": "196e0354-ea0f-4547-a3df-e04633b704f6"
    }
  ]
}

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/addAll
Content-Type: application/json

 [
    {
      "type": "Setup",
      "source": "test1",
      "commandName": "setup-iris",
      "maybeObsId": "test-obsId1",
      "paramSet": [
        {
          "keyName": "myStruct",
          "keyType": "StructKey",
          "values": [
            {
              "paramSet": [
                {
                  "keyName": "ra",
                  "keyType": "StringKey",
                  "values": [
                    "12:13:14.1"
                  ],
                  "units": "NoUnits"
                },
                {
                  "keyName": "dec",
                  "keyType": "StringKey",
                  "values": [
                    "32:33:34.4"
                  ],
                  "units": "NoUnits"
                },
                {
                  "keyName": "epoch",
                  "keyType": "DoubleKey",
                  "values": [
                    1950.0
                  ],
                  "units": "NoUnits"
                }
              ]
            }
          ],
          "units": "NoUnits"
        }
      ],
      "runId": "196e0354-ea0f-4547-a3df-e04633b704f3"
    }
]

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/pause
Content-Type: application/json

{}

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/resume
Content-Type: application/json

{}

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/reset
Content-Type: application/json

{}

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/prepend
Content-Type: application/json


[
  {
    "type": "Setup",
    "source": "test1",
    "commandName": "setup-iris",
    "maybeObsId": "test-obsId1",
    "paramSet": [
      {
        "keyName": "myStruct",
        "keyType": "StructKey",
        "values": [
          {
            "paramSet": [
              {
                "keyName": "ra",
                "keyType": "StringKey",
                "values": [
                  "12:13:14.1"
                ],
                "units": "NoUnits"
              },
              {
                "keyName": "dec",
                "keyType": "StringKey",
                "values": [
                  "32:33:34.4"
                ],
                "units": "NoUnits"
              },
              {
                "keyName": "epoch",
                "keyType": "DoubleKey",
                "values": [
                  1950.0
                ],
                "units": "NoUnits"
              }
            ]
          }
        ],
        "units": "NoUnits"
      }
    ],
    "runId": "196e0354-ea0f-4547-a3df-e04633b612f8"
  }
 ]

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/prepend
Content-Type: application/json

[
  {
    "type": "Setup",
    "source": "test1",
    "commandName": "setup-iris",
    "maybeObsId": "test-obsId1",
    "paramSet": [
      {
        "keyName": "myStruct",
        "keyType": "StructKey",
        "values": [
          {
            "paramSet": [
              {
                "keyName": "ra",
                "keyType": "StringKey",
                "values": [
                  "12:13:14.1"
                ],
                "units": "NoUnits"
              },
              {
                "keyName": "dec",
                "keyType": "StringKey",
                "values": [
                  "32:33:34.4"
                ],
                "units": "NoUnits"
              },
              {
                "keyName": "epoch",
                "keyType": "DoubleKey",
                "values": [
                  1950.0
                ],
                "units": "NoUnits"
              }
            ]
          }
        ],
        "units": "NoUnits"
      }
    ],
    "runId": "196e0354-ea0f-4547-c3df-e04633b704e8"
  }
]

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/shutdown
Content-Type: application/json

{}

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/sequence
Content-Type: application/json

{}

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/addBreakpoints
Content-Type: application/json

["196e0354-ea0f-4547-a3df-e04633b704f9"]

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/removeBreakpoints
Content-Type: application/json

["196e0354-ea0f-4547-a3df-e04633b704f9"]

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/delete
Content-Type: application/json

["196e0354-ea0f-4547-a3df-e04633b704f9"]

### Send POST request with json body
POST http://localhost:9090/sequencer/iris/darknight/editor/replace
Content-Type: application/json

[ "ac37a334-fbda-4234-9166-f14020c52ac8",
    [{
      "type": "Setup",
      "source": "test1",
      "commandName": "setup-iris",
      "maybeObsId": "test-replace",
      "paramSet": [
        {
          "keyName": "myStruct",
          "keyType": "StructKey",
          "values": [
            {
              "paramSet": [
                {
                  "keyName": "ra",
                  "keyType": "StringKey",
                  "values": [
                    "12:13:14.1"
                  ],
                  "units": "NoUnits"
                },
                {
                  "keyName": "dec",
                  "keyType": "StringKey",
                  "values": [
                    "32:33:34.4"
                  ],
                  "units": "NoUnits"
                },
                {
                  "keyName": "epoch",
                  "keyType": "DoubleKey",
                  "values": [
                    1950.0
                  ],
                  "units": "NoUnits"
                }
              ]
            }
          ],
          "units": "NoUnits"
        }
      ],
      "runId": "196e0354-eb0f-4547-a3ef-e04633b704g8"
    }]
]



